### PR TITLE
YANG model updates for IETF 101

### PR DESCRIPTION
**Pull request by efralaz**
Review of path-computation to resolve issues

### CODE REVIEW

**Comment by italobusi** [comment]
This pull request proposes resolutions for open issues #22 and #29 

It also proposes partial resolution for open issues #16 and #31 : pending further clarification or updates of the TE models

It also includes the proposed changes in pull request #33

**Comment by italobusi** [comment]
https://github.com/rvilalta/ietf-te-path-computation/blob/cbc9e0f84b1b01b5ddf02de0f0234fadf3cf5f7d/ietf-te-path-computation.yang#L314

Please align with naming convention used in other modules:

`list request {`

or (better for me)

`list path-request {`

**Comment by italobusi** [comment]
https://github.com/rvilalta/ietf-te-path-computation/blob/cbc9e0f84b1b01b5ddf02de0f0234fadf3cf5f7d/ietf-te-path-computation.yang#L227

https://github.com/rvilalta/ietf-te-path-computation/blob/cbc9e0f84b1b01b5ddf02de0f0234fadf3cf5f7d/ietf-te-path-computation.yang#L315

https://github.com/rvilalta/ietf-te-path-computation/blob/cbc9e0f84b1b01b5ddf02de0f0234fadf3cf5f7d/ietf-te-path-computation.yang#L336

Please align the naming conventions

Proposal:

```
      key request-id;
...
      key synchronization-id;
...
      key response-id;
```

**Comment by italobusi** [comment]
https://github.com/rvilalta/ietf-te-path-computation/blob/cbc9e0f84b1b01b5ddf02de0f0234fadf3cf5f7d/ietf-te-path-computation.yang#L351

Please align with naming convention:

`          container path {`

**Comment by italobusi** [comment]
https://github.com/rvilalta/ietf-te-path-computation/blob/cbc9e0f84b1b01b5ddf02de0f0234fadf3cf5f7d/ietf-te-path-computation.yang#L290-L292

Please make it a presence container

**Comment by efralaz** [comment]
Done!

**Comment by italobusi** [comment]
Could you please also recompile and upload the updated YANG trees?

**Comment by efralaz** [comment]
Done. Fixed also a couple of types, which have been moved from ietf-te to ietf-te-types. 
Please note: path-optimization has "gained" a couple of attributes in ietf-te-types : include-resources and exclude-resources have been added probably to model the relaxable metrics (only include and exclude).
Too bad for me, but that is it. I'll come back and rediscuss this issue after IETF 101.

**Comment by italobusi** [comment]
Updated YANG model included in the -01 draft, just been submitted for IETF 101

@rvilalta : please review the changes and if you are ok, please merge this pull request

**Pull request merged**
